// flow-typed signature: 35dbd6e51e31b9e20b35d103feccb37c
// flow-typed version: <<STUB>>/backoff_v2.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backoff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'backoff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backoff/lib/backoff' {
  declare module.exports: any;
}

declare module 'backoff/lib/function_call' {
  declare module.exports: any;
}

declare module 'backoff/lib/strategy/exponential' {
  declare module.exports: any;
}

declare module 'backoff/lib/strategy/fibonacci' {
  declare module.exports: any;
}

declare module 'backoff/lib/strategy/strategy' {
  declare module.exports: any;
}

declare module 'backoff/tests/api' {
  declare module.exports: any;
}

declare module 'backoff/tests/backoff_strategy' {
  declare module.exports: any;
}

declare module 'backoff/tests/backoff' {
  declare module.exports: any;
}

declare module 'backoff/tests/exponential_backoff_strategy' {
  declare module.exports: any;
}

declare module 'backoff/tests/fibonacci_backoff_strategy' {
  declare module.exports: any;
}

declare module 'backoff/tests/function_call' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backoff/index' {
  declare module.exports: $Exports<'backoff'>;
}
declare module 'backoff/index.js' {
  declare module.exports: $Exports<'backoff'>;
}
declare module 'backoff/lib/backoff.js' {
  declare module.exports: $Exports<'backoff/lib/backoff'>;
}
declare module 'backoff/lib/function_call.js' {
  declare module.exports: $Exports<'backoff/lib/function_call'>;
}
declare module 'backoff/lib/strategy/exponential.js' {
  declare module.exports: $Exports<'backoff/lib/strategy/exponential'>;
}
declare module 'backoff/lib/strategy/fibonacci.js' {
  declare module.exports: $Exports<'backoff/lib/strategy/fibonacci'>;
}
declare module 'backoff/lib/strategy/strategy.js' {
  declare module.exports: $Exports<'backoff/lib/strategy/strategy'>;
}
declare module 'backoff/tests/api.js' {
  declare module.exports: $Exports<'backoff/tests/api'>;
}
declare module 'backoff/tests/backoff_strategy.js' {
  declare module.exports: $Exports<'backoff/tests/backoff_strategy'>;
}
declare module 'backoff/tests/backoff.js' {
  declare module.exports: $Exports<'backoff/tests/backoff'>;
}
declare module 'backoff/tests/exponential_backoff_strategy.js' {
  declare module.exports: $Exports<'backoff/tests/exponential_backoff_strategy'>;
}
declare module 'backoff/tests/fibonacci_backoff_strategy.js' {
  declare module.exports: $Exports<'backoff/tests/fibonacci_backoff_strategy'>;
}
declare module 'backoff/tests/function_call.js' {
  declare module.exports: $Exports<'backoff/tests/function_call'>;
}
