// flow-typed signature: 1c04fe8c2cff5d0721ea258b4e3731eb
// flow-typed version: <<STUB>>/hubot_v2.19.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hubot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hubot' {
  declare module.exports: any;
}
