// flow-typed signature: 653958968581121dd5817c20c85ee03b
// flow-typed version: <<STUB>>/memoizee_v0.4.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memoizee'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'memoizee' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memoizee/benchmark/fibonacci' {
  declare module.exports: any;
}

declare module 'memoizee/ext/async' {
  declare module.exports: any;
}

declare module 'memoizee/ext/dispose' {
  declare module.exports: any;
}

declare module 'memoizee/ext/max-age' {
  declare module.exports: any;
}

declare module 'memoizee/ext/max' {
  declare module.exports: any;
}

declare module 'memoizee/ext/promise' {
  declare module.exports: any;
}

declare module 'memoizee/ext/ref-counter' {
  declare module.exports: any;
}

declare module 'memoizee/lib/configure-map' {
  declare module.exports: any;
}

declare module 'memoizee/lib/methods' {
  declare module.exports: any;
}

declare module 'memoizee/lib/registered-extensions' {
  declare module.exports: any;
}

declare module 'memoizee/lib/resolve-length' {
  declare module.exports: any;
}

declare module 'memoizee/lib/resolve-normalize' {
  declare module.exports: any;
}

declare module 'memoizee/lib/resolve-resolve' {
  declare module.exports: any;
}

declare module 'memoizee/lib/weak' {
  declare module.exports: any;
}

declare module 'memoizee/methods-plain' {
  declare module.exports: any;
}

declare module 'memoizee/methods' {
  declare module.exports: any;
}

declare module 'memoizee/normalizers/get-1' {
  declare module.exports: any;
}

declare module 'memoizee/normalizers/get-fixed' {
  declare module.exports: any;
}

declare module 'memoizee/normalizers/get-primitive-fixed' {
  declare module.exports: any;
}

declare module 'memoizee/normalizers/get' {
  declare module.exports: any;
}

declare module 'memoizee/normalizers/primitive' {
  declare module.exports: any;
}

declare module 'memoizee/plain' {
  declare module.exports: any;
}

declare module 'memoizee/profile' {
  declare module.exports: any;
}

declare module 'memoizee/test/ext/async' {
  declare module.exports: any;
}

declare module 'memoizee/test/ext/dispose' {
  declare module.exports: any;
}

declare module 'memoizee/test/ext/max-age' {
  declare module.exports: any;
}

declare module 'memoizee/test/ext/max' {
  declare module.exports: any;
}

declare module 'memoizee/test/ext/promise' {
  declare module.exports: any;
}

declare module 'memoizee/test/ext/ref-counter' {
  declare module.exports: any;
}

declare module 'memoizee/test/index' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/configure-map' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/methods' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/registered-extensions' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/resolve-length' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/resolve-normalize' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/resolve-resolve' {
  declare module.exports: any;
}

declare module 'memoizee/test/lib/weak' {
  declare module.exports: any;
}

declare module 'memoizee/test/methods-plain' {
  declare module.exports: any;
}

declare module 'memoizee/test/methods' {
  declare module.exports: any;
}

declare module 'memoizee/test/normalizers/get-1' {
  declare module.exports: any;
}

declare module 'memoizee/test/normalizers/get-fixed' {
  declare module.exports: any;
}

declare module 'memoizee/test/normalizers/get-primitive-fixed' {
  declare module.exports: any;
}

declare module 'memoizee/test/normalizers/get' {
  declare module.exports: any;
}

declare module 'memoizee/test/normalizers/primitive' {
  declare module.exports: any;
}

declare module 'memoizee/test/plain' {
  declare module.exports: any;
}

declare module 'memoizee/test/profile' {
  declare module.exports: any;
}

declare module 'memoizee/test/weak-plain' {
  declare module.exports: any;
}

declare module 'memoizee/test/weak' {
  declare module.exports: any;
}

declare module 'memoizee/weak-plain' {
  declare module.exports: any;
}

declare module 'memoizee/weak' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memoizee/benchmark/fibonacci.js' {
  declare module.exports: $Exports<'memoizee/benchmark/fibonacci'>;
}
declare module 'memoizee/ext/async.js' {
  declare module.exports: $Exports<'memoizee/ext/async'>;
}
declare module 'memoizee/ext/dispose.js' {
  declare module.exports: $Exports<'memoizee/ext/dispose'>;
}
declare module 'memoizee/ext/max-age.js' {
  declare module.exports: $Exports<'memoizee/ext/max-age'>;
}
declare module 'memoizee/ext/max.js' {
  declare module.exports: $Exports<'memoizee/ext/max'>;
}
declare module 'memoizee/ext/promise.js' {
  declare module.exports: $Exports<'memoizee/ext/promise'>;
}
declare module 'memoizee/ext/ref-counter.js' {
  declare module.exports: $Exports<'memoizee/ext/ref-counter'>;
}
declare module 'memoizee/index' {
  declare module.exports: $Exports<'memoizee'>;
}
declare module 'memoizee/index.js' {
  declare module.exports: $Exports<'memoizee'>;
}
declare module 'memoizee/lib/configure-map.js' {
  declare module.exports: $Exports<'memoizee/lib/configure-map'>;
}
declare module 'memoizee/lib/methods.js' {
  declare module.exports: $Exports<'memoizee/lib/methods'>;
}
declare module 'memoizee/lib/registered-extensions.js' {
  declare module.exports: $Exports<'memoizee/lib/registered-extensions'>;
}
declare module 'memoizee/lib/resolve-length.js' {
  declare module.exports: $Exports<'memoizee/lib/resolve-length'>;
}
declare module 'memoizee/lib/resolve-normalize.js' {
  declare module.exports: $Exports<'memoizee/lib/resolve-normalize'>;
}
declare module 'memoizee/lib/resolve-resolve.js' {
  declare module.exports: $Exports<'memoizee/lib/resolve-resolve'>;
}
declare module 'memoizee/lib/weak.js' {
  declare module.exports: $Exports<'memoizee/lib/weak'>;
}
declare module 'memoizee/methods-plain.js' {
  declare module.exports: $Exports<'memoizee/methods-plain'>;
}
declare module 'memoizee/methods.js' {
  declare module.exports: $Exports<'memoizee/methods'>;
}
declare module 'memoizee/normalizers/get-1.js' {
  declare module.exports: $Exports<'memoizee/normalizers/get-1'>;
}
declare module 'memoizee/normalizers/get-fixed.js' {
  declare module.exports: $Exports<'memoizee/normalizers/get-fixed'>;
}
declare module 'memoizee/normalizers/get-primitive-fixed.js' {
  declare module.exports: $Exports<'memoizee/normalizers/get-primitive-fixed'>;
}
declare module 'memoizee/normalizers/get.js' {
  declare module.exports: $Exports<'memoizee/normalizers/get'>;
}
declare module 'memoizee/normalizers/primitive.js' {
  declare module.exports: $Exports<'memoizee/normalizers/primitive'>;
}
declare module 'memoizee/plain.js' {
  declare module.exports: $Exports<'memoizee/plain'>;
}
declare module 'memoizee/profile.js' {
  declare module.exports: $Exports<'memoizee/profile'>;
}
declare module 'memoizee/test/ext/async.js' {
  declare module.exports: $Exports<'memoizee/test/ext/async'>;
}
declare module 'memoizee/test/ext/dispose.js' {
  declare module.exports: $Exports<'memoizee/test/ext/dispose'>;
}
declare module 'memoizee/test/ext/max-age.js' {
  declare module.exports: $Exports<'memoizee/test/ext/max-age'>;
}
declare module 'memoizee/test/ext/max.js' {
  declare module.exports: $Exports<'memoizee/test/ext/max'>;
}
declare module 'memoizee/test/ext/promise.js' {
  declare module.exports: $Exports<'memoizee/test/ext/promise'>;
}
declare module 'memoizee/test/ext/ref-counter.js' {
  declare module.exports: $Exports<'memoizee/test/ext/ref-counter'>;
}
declare module 'memoizee/test/index.js' {
  declare module.exports: $Exports<'memoizee/test/index'>;
}
declare module 'memoizee/test/lib/configure-map.js' {
  declare module.exports: $Exports<'memoizee/test/lib/configure-map'>;
}
declare module 'memoizee/test/lib/methods.js' {
  declare module.exports: $Exports<'memoizee/test/lib/methods'>;
}
declare module 'memoizee/test/lib/registered-extensions.js' {
  declare module.exports: $Exports<'memoizee/test/lib/registered-extensions'>;
}
declare module 'memoizee/test/lib/resolve-length.js' {
  declare module.exports: $Exports<'memoizee/test/lib/resolve-length'>;
}
declare module 'memoizee/test/lib/resolve-normalize.js' {
  declare module.exports: $Exports<'memoizee/test/lib/resolve-normalize'>;
}
declare module 'memoizee/test/lib/resolve-resolve.js' {
  declare module.exports: $Exports<'memoizee/test/lib/resolve-resolve'>;
}
declare module 'memoizee/test/lib/weak.js' {
  declare module.exports: $Exports<'memoizee/test/lib/weak'>;
}
declare module 'memoizee/test/methods-plain.js' {
  declare module.exports: $Exports<'memoizee/test/methods-plain'>;
}
declare module 'memoizee/test/methods.js' {
  declare module.exports: $Exports<'memoizee/test/methods'>;
}
declare module 'memoizee/test/normalizers/get-1.js' {
  declare module.exports: $Exports<'memoizee/test/normalizers/get-1'>;
}
declare module 'memoizee/test/normalizers/get-fixed.js' {
  declare module.exports: $Exports<'memoizee/test/normalizers/get-fixed'>;
}
declare module 'memoizee/test/normalizers/get-primitive-fixed.js' {
  declare module.exports: $Exports<'memoizee/test/normalizers/get-primitive-fixed'>;
}
declare module 'memoizee/test/normalizers/get.js' {
  declare module.exports: $Exports<'memoizee/test/normalizers/get'>;
}
declare module 'memoizee/test/normalizers/primitive.js' {
  declare module.exports: $Exports<'memoizee/test/normalizers/primitive'>;
}
declare module 'memoizee/test/plain.js' {
  declare module.exports: $Exports<'memoizee/test/plain'>;
}
declare module 'memoizee/test/profile.js' {
  declare module.exports: $Exports<'memoizee/test/profile'>;
}
declare module 'memoizee/test/weak-plain.js' {
  declare module.exports: $Exports<'memoizee/test/weak-plain'>;
}
declare module 'memoizee/test/weak.js' {
  declare module.exports: $Exports<'memoizee/test/weak'>;
}
declare module 'memoizee/weak-plain.js' {
  declare module.exports: $Exports<'memoizee/weak-plain'>;
}
declare module 'memoizee/weak.js' {
  declare module.exports: $Exports<'memoizee/weak'>;
}
